"use client";

import { useMemo } from "react";
import { useRouter } from "next/navigation";
import { RaniAction } from "@/types/rani";
import { buildRaniContext } from "@/lib/rani/buildRaniContext";
import { useRaniConversation } from "@/hooks/useRaniConversation";
import { resolveRaniAction } from "@/lib/rani/resolveRaniActions";
import { ExploreLayerId, ExploreModeId } from "@/data/exploreControls";
import { RegionId } from "@/types/region";
import { usePassportProgressSummary } from "@/hooks/usePassportProgressSummary";
import { RecommendedJourney } from "@/data/journeys/types";
import { useLanguage } from "@/context/app-context";

import { RaniEditorialHeader } from "./RaniEditorialHeader";
import { RaniPassportJourneyPath } from "./RaniPassportJourneyPath";
import { RaniProactiveRecommendation } from "./RaniProactiveRecommendation";
import { RaniTaskSelector } from "./RaniTaskSelector";
import { RaniConversationJournal } from "./RaniConversationJournal";
import { RaniComposer } from "./RaniComposer";

type Props = {
  activeMode: ExploreModeId;
  activeLayer: ExploreLayerId;
  selectedProvinceId: string | null;
  searchQuery: string;
  showFlagshipOnly: boolean;
  highlightedRegionId: RegionId | null;
  activeJourney: RecommendedJourney | null;
  onExploreMapRegion: (regionId: string) => void;
  onOpenSummary: (provinceId: string) => void;
  onOpenAtlas: (provinceId: string) => void;
};

export function RaniMapAssistantSection({
  activeMode,
  activeLayer,
  selectedProvinceId,
  searchQuery,
  showFlagshipOnly,
  highlightedRegionId,
  activeJourney,
  onExploreMapRegion,
  onOpenSummary,
  onOpenAtlas,
}: Props) {
  const router = useRouter();
  const passportSummary = usePassportProgressSummary(highlightedRegionId, selectedProvinceId);
  const { language } = useLanguage();
  
  const context = useMemo(() => {
    return buildRaniContext({
      locale: language, 
      activeMode,
      activeLayer,
      selectedProvinceId,
      searchQuery,
      showFlagshipOnly,
      activeRegionId: highlightedRegionId,
      highlightedRegionId,
      activeJourneyId: activeJourney?.id || null,
      journeyProvinceIds: activeJourney ? activeJourney.stops.map(s => s.provinceId).filter((id): id is string => Boolean(id)) : [],
      plannedProvinceIds: passportSummary.planned,
      startedProvinceIds: passportSummary.started,
      completedProvinceIds: passportSummary.completed,
      latestAchievementId: passportSummary.latestAchievement?.id || null,
      nextMilestone: passportSummary.nextMilestone,
      entrySource: "section-scroll",
    });
  }, [
    activeMode,
    activeLayer,
    selectedProvinceId,
    searchQuery,
    showFlagshipOnly,
    highlightedRegionId,
    activeJourney,
    passportSummary,
    language
  ]);

  const {
    conversation,
    quickPrompts,
    submitQuery,
  } = useRaniConversation({ context });

  const handleAction = (action: RaniAction) => {
    resolveRaniAction({
      action,
      onExploreMapRegion,
      onOpenSummary,
      onOpenAtlas,
      router
    });
  };

  const proactiveResponse = useMemo(() => {
    // The proactive recommendation is always the first system message if it's generated by 'local' proactively
    if (conversation.messages.length > 0) {
      const firstMsg = conversation.messages[0];
      if (firstMsg.role === "rani" && firstMsg.response && conversation.generatedBy === "local") {
        return firstMsg.response;
      }
    }
    return null;
  }, [conversation]);

  return (
    <section 
      id="rani-map-assistant" 
      aria-labelledby="rani-map-assistant-heading"
      className="relative w-full py-20 md:py-32 bg-[rgba(251,247,239,0.68)] overflow-hidden scroll-mt-24 lg:scroll-mt-32 border-t border-[#DED3C3]"
    >
      <div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 relative z-10">
        
        <RaniEditorialHeader />

        {/* Editorial Canvas Asymmetric Layout */}
        <div className="flex flex-col lg:flex-row items-stretch gap-6 lg:gap-8 mb-16">
           {/* Left Column: Context Snapshot */}
           <div className="w-full lg:w-4/12 flex flex-col gap-6">
              <RaniPassportJourneyPath context={context} />
           </div>

           {/* Right Column: Proactive Recommendation */}
           <div className="w-full lg:w-8/12">
              <RaniProactiveRecommendation 
                response={proactiveResponse} 
                onAction={handleAction} 
              />
           </div>
        </div>

        <div className="max-w-4xl mx-auto">
          <RaniTaskSelector 
            prompts={quickPrompts} 
            onSelect={submitQuery} 
            disabled={conversation.status === "loading"}
          />
          
          <RaniConversationJournal 
            conversation={conversation} 
            onAction={handleAction} 
          />
          
          <RaniComposer 
            onSend={submitQuery} 
            disabled={conversation.status === "loading"}
          />
        </div>

      </div>
    </section>
  );
}
