export const stampAssetMap: Record<string, string> = {
  "aceh": "/assets/passport/stamps/aceh.png",
  "bali": "/assets/passport/stamps/bali.png",
  "banten": "/assets/passport/stamps/banten.png",
  "bengkulu": "/assets/passport/stamps/bengkulu.png",
  "di-yogyakarta": "/assets/passport/stamps/di-yogyakarta.png",
  "dki-jakarta": "/assets/passport/stamps/dki-jakarta.png",
  "gorontalo": "/assets/passport/stamps/gorontalo.png",
  "jambi": "/assets/passport/stamps/jambi.png",
  "jawa-barat": "/assets/passport/stamps/jawa-barat.png",
  "jawa-tengah": "/assets/passport/stamps/jawa-tengah.png",
  "jawa-timur": "/assets/passport/stamps/jawa-timur.png",
  "kalimantan-barat": "/assets/passport/stamps/kalimantan-barat.png",
  "kalimantan-selatan": "/assets/passport/stamps/kalimantan-selatan.png",
  "kalimantan-tengah": "/assets/passport/stamps/kalimantan-tengah.png",
  "kalimantan-timur": "/assets/passport/stamps/kalimantan-timur.png",
  "kalimantan-utara": "/assets/passport/stamps/kalimantan-utara.png",
  "kepulauan-bangka-belitung": "/assets/passport/stamps/bangka-belitung.png", // Correct mismatch
  "kepulauan-riau": "/assets/passport/stamps/kepulauan-riau.png",
  "lampung": "/assets/passport/stamps/lampung.png",
  "maluku-utara": "/assets/passport/stamps/maluku-utara.png",
  "maluku": "/assets/passport/stamps/maluku.png",
  "nusa-tenggara-barat": "/assets/passport/stamps/nusa-tenggara-barat.png",
  "nusa-tenggara-timur": "/assets/passport/stamps/nusa-tenggara-timur.png",
  "papua-barat-daya": "/assets/passport/stamps/papua-barat-daya.png",
  "papua-barat": "/assets/passport/stamps/papua-barat.png",
  "papua-pegunungan": "/assets/passport/stamps/papua-pegunungan.png",
  "papua-selatan": "/assets/passport/stamps/papua-selatan.png",
  "papua-tengah": "/assets/passport/stamps/papua-tengah.png",
  "papua": "/assets/passport/stamps/papua.png",
  "riau": "/assets/passport/stamps/riau.png",
  "sulawesi-barat": "/assets/passport/stamps/sulawesi-barat.png",
  "sulawesi-selatan": "/assets/passport/stamps/sulawesi-selatan.png",
  "sulawesi-tengah": "/assets/passport/stamps/sulawesi-tengah.png",
  "sulawesi-tenggara": "/assets/passport/stamps/sulawesi-tenggara.png",
  "sulawesi-utara": "/assets/passport/stamps/sulawesi-utara.png",
  "sumatera-barat": "/assets/passport/stamps/sumatera-barat.png",
  "sumatera-selatan": "/assets/passport/stamps/sumatera-selatan.png",
  "sumatera-utara": "/assets/passport/stamps/sumatera-utara.png",
};

export function getStampAsset(provinceId: string): string | null {
  return stampAssetMap[provinceId] || null;
}
